package com.ia.hibernatepersistent;

import java.io.Serializable;

public interface IPersistent extends Serializable {

	Serializable getId();

	void setId(Serializable id);

	boolean isPersisted();
	
	public boolean hasAutoGeneratedId();

}
